import { VenueConfig } from "./types";

const PI = Math.PI;

// Shared defaults for new sections
const ARC_DEFAULTS = {
  type: "arc" as const,
  x: 0,
  z: 0,
  facing: 0,
};

const RECT_DEFAULTS = {
  type: "rectangular" as const,
  startAngle: 0,
  endAngle: 0,
};

export const venuePresets: Record<string, VenueConfig> = {
  arena: {
    name: "Grand Arena",
    stageRadius: 8,
    rowSpacing: 1.4,
    seatSpacing: 0.8,
    sections: [
      {
        ...ARC_DEFAULTS,
        id: "A",
        label: "Section A",
        startAngle: -PI * 0.4,
        endAngle: PI * 0.4,
        rows: 8,
        seatsPerRow: 24,
        elevation: 0.5,
        tilt: 0.35,
        color: "#3b82f6",
      },
      {
        ...ARC_DEFAULTS,
        id: "B",
        label: "Section B",
        startAngle: PI * 0.45,
        endAngle: PI * 0.95,
        rows: 8,
        seatsPerRow: 16,
        elevation: 0.5,
        tilt: 0.35,
        color: "#10b981",
      },
      {
        ...ARC_DEFAULTS,
        id: "C",
        label: "Section C",
        startAngle: PI * 1.0,
        endAngle: PI * 1.6,
        rows: 8,
        seatsPerRow: 24,
        elevation: 0.5,
        tilt: 0.35,
        color: "#f59e0b",
      },
      {
        ...ARC_DEFAULTS,
        id: "D",
        label: "Section D",
        startAngle: PI * 1.65,
        endAngle: PI * 1.95,
        rows: 6,
        seatsPerRow: 10,
        elevation: 0.5,
        tilt: 0.35,
        color: "#ef4444",
      },
      {
        ...ARC_DEFAULTS,
        id: "U1",
        label: "VIP A",
        startAngle: -PI * 0.35,
        endAngle: PI * 0.35,
        rows: 5,
        seatsPerRow: 30,
        elevation: 4,
        tilt: 0.5,
        color: "#8b5cf6",
      },
      {
        ...ARC_DEFAULTS,
        id: "U2",
        label: "VVIP C",
        startAngle: PI * 1.05,
        endAngle: PI * 1.55,
        rows: 5,
        seatsPerRow: 30,
        elevation: 4,
        tilt: 0.5,
        color: "#ec4899",
      },
    ],
  },

  amphitheater: {
    name: "Amphitheater",
    stageRadius: 6,
    rowSpacing: 1.3,
    seatSpacing: 0.8,
    sections: [
      {
        ...ARC_DEFAULTS,
        id: "L",
        label: "Left Wing",
        startAngle: PI * 0.55,
        endAngle: PI * 0.95,
        rows: 10,
        seatsPerRow: 14,
        elevation: 0.3,
        tilt: 0.3,
        color: "#10b981",
      },
      {
        ...ARC_DEFAULTS,
        id: "C",
        label: "Center",
        startAngle: PI * 0.15,
        endAngle: PI * 0.5,
        rows: 10,
        seatsPerRow: 20,
        elevation: 0.3,
        tilt: 0.3,
        color: "#3b82f6",
      },
      {
        ...ARC_DEFAULTS,
        id: "R",
        label: "Right Wing",
        startAngle: -PI * 0.05,
        endAngle: PI * 0.1,
        rows: 10,
        seatsPerRow: 8,
        elevation: 0.3,
        tilt: 0.3,
        color: "#f59e0b",
      },
      {
        ...ARC_DEFAULTS,
        id: "VIP",
        label: "VIP Balcony",
        startAngle: PI * 0.25,
        endAngle: PI * 0.75,
        rows: 4,
        seatsPerRow: 20,
        elevation: 5,
        tilt: 0.6,
        color: "#8b5cf6",
      },
    ],
  },

  theater: {
    name: "Grand Theater",
    stageRadius: 5,
    rowSpacing: 1.2,
    seatSpacing: 0.9,
    sections: [
      {
        ...RECT_DEFAULTS,
        id: "OL",
        label: "Orchestra Left",
        x: 0,
        z: -6,
        facing: PI * 0.55,
        rows: 10,
        seatsPerRow: 12,
        elevation: 0.2,
        tilt: 0.15,
        color: "#3b82f6",
      },
      {
        ...RECT_DEFAULTS,
        id: "OC",
        label: "Orchestra Center",
        x: 0,
        z: 0,
        facing: PI * 0.5,
        rows: 12,
        seatsPerRow: 18,
        elevation: 0.2,
        tilt: 0.15,
        color: "#10b981",
      },
      {
        ...RECT_DEFAULTS,
        id: "OR",
        label: "Orchestra Right",
        x: 0,
        z: 6,
        facing: PI * 0.45,
        rows: 10,
        seatsPerRow: 12,
        elevation: 0.2,
        tilt: 0.15,
        color: "#f59e0b",
      },
      {
        ...RECT_DEFAULTS,
        id: "BL",
        label: "Balcony Left",
        x: 0,
        z: -5,
        facing: PI * 0.55,
        rows: 6,
        seatsPerRow: 10,
        elevation: 4,
        tilt: 0.5,
        color: "#8b5cf6",
      },
      {
        ...RECT_DEFAULTS,
        id: "BC",
        label: "Balcony Center",
        x: 0,
        z: 0,
        facing: PI * 0.5,
        rows: 6,
        seatsPerRow: 16,
        elevation: 4,
        tilt: 0.5,
        color: "#ec4899",
      },
      {
        ...RECT_DEFAULTS,
        id: "BR",
        label: "Balcony Right",
        x: 0,
        z: 5,
        facing: PI * 0.45,
        rows: 6,
        seatsPerRow: 10,
        elevation: 4,
        tilt: 0.5,
        color: "#ef4444",
      },
    ],
  },
};

export const defaultVenueConfig: VenueConfig = venuePresets.arena;
